/** Atomic permission keys — keep in sync with app_permissions seed. */
export const PERMISSION_KEYS = [
  "profile:read",
  "settings:read",
  "settings:expense_types:read",
  "settings:expense_types:write",
  "settings:expense_types:delete",
  "settings:income_types:read",
  "settings:income_types:write",
  "settings:income_types:delete",
  "settings:ministry_categories:read",
  "settings:ministry_categories:write",
  "settings:ministry_categories:delete",
  "settings:church:read",
  "settings:church:write",
  "settings:discount_templates:write",
  "network:churches:read",
  "dashboard:read",
  "members:read",
  "members:write",
  "members:delete",
  "ministerios:read",
  "ministerios:write",
  "ministerios:write_own",
  "eventos:read",
  "eventos:write",
  "eventos:write_own",
  "eventos:delete",
  "attendance:read",
  "attendance:write",
  "comunicacion:read",
  "comunicacion:write",
  "comunicacion:delete",
  "finances:funds:read",
  "finances:funds:write",
  "finances:funds:delete",
  "finances:funds:export",
  "finances:transactions:read",
  "finances:transactions:write",
  "finances:transactions:authorize",
  "finances:transactions:delete",
  "finances:transactions:export",
  "finances:contributions:read",
  "finances:contributions:write",
  "finances:contributions:delete",
  "finances:contributions:export",
  "finances:tithe_close:read",
  "finances:tithe_close:write",
  "admin_users:manage",
  "roles:manage",
  "audit:read",
  "audit:export",
  "reports:financial_monthly_cead:read",
  "reports:financial_monthly_cead:export",
  "reports:financial_monthly_concilio_f001:read",
  "reports:financial_monthly_concilio_f001:export",
  "reports:membership_directory:read",
  "reports:membership_directory:export",
  "reports:membership_annual_cead:read",
  "reports:membership_annual_cead:export",
  "reports:executive_monthly_summary:read",
  "reports:executive_monthly_summary:export",
  "reports:financial_income_expense:read",
  "reports:financial_income_expense:export",
  "reports:financial_by_fund:read",
  "reports:financial_by_fund:export",
  "reports:financial_by_member:read",
  "reports:financial_by_member:export",
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];

export const FINANCE_READ_PERMISSIONS = [
  "finances:funds:read",
  "finances:transactions:read",
  "finances:contributions:read",
  "finances:tithe_close:read",
] as const satisfies readonly PermissionKey[];

export function isPermissionKey(value: string): value is PermissionKey {
  return (PERMISSION_KEYS as readonly string[]).includes(value);
}

export { expandPermissionKeys as parsePermissionKeys } from "@/lib/auth/finance-permission-bridge";
