-- P2.x — CRUD categorías de ministerios por iglesia.
-- Reemplaza CHECK enum de 20260713240000 por tabla + FK (church_id, code).
-- Seeds: discipleship, house_group, cell_group (Célula), children, worship, other.

-- ---------------------------------------------------------------------------
-- Permissions
-- ---------------------------------------------------------------------------

INSERT INTO public.app_permissions (permission_key, module, action, description) VALUES
  ('settings:ministry_categories:read', 'settings', 'read', 'Ver categorías de ministerios'),
  ('settings:ministry_categories:write', 'settings', 'write', 'Crear y editar categorías de ministerios'),
  ('settings:ministry_categories:delete', 'settings', 'delete', 'Eliminar categorías de ministerios')
ON CONFLICT (permission_key) DO NOTHING;

INSERT INTO public.app_role_permissions (app_role_id, permission_key)
SELECT DISTINCT arp.app_role_id, 'settings:ministry_categories:read'
FROM public.app_role_permissions arp
WHERE arp.permission_key = 'settings:income_types:read'
ON CONFLICT DO NOTHING;

INSERT INTO public.app_role_permissions (app_role_id, permission_key)
SELECT DISTINCT arp.app_role_id, 'settings:ministry_categories:write'
FROM public.app_role_permissions arp
WHERE arp.permission_key = 'settings:income_types:write'
ON CONFLICT DO NOTHING;

INSERT INTO public.app_role_permissions (app_role_id, permission_key)
SELECT DISTINCT arp.app_role_id, 'settings:ministry_categories:delete'
FROM public.app_role_permissions arp
WHERE arp.permission_key = 'settings:income_types:delete'
ON CONFLICT DO NOTHING;

INSERT INTO public.church_role_permissions (church_id, app_role_id, permission_key)
SELECT DISTINCT crp.church_id, crp.app_role_id, 'settings:ministry_categories:read'
FROM public.church_role_permissions crp
WHERE crp.permission_key = 'settings:income_types:read'
ON CONFLICT DO NOTHING;

INSERT INTO public.church_role_permissions (church_id, app_role_id, permission_key)
SELECT DISTINCT crp.church_id, crp.app_role_id, 'settings:ministry_categories:write'
FROM public.church_role_permissions crp
WHERE crp.permission_key = 'settings:income_types:write'
ON CONFLICT DO NOTHING;

INSERT INTO public.church_role_permissions (church_id, app_role_id, permission_key)
SELECT DISTINCT crp.church_id, crp.app_role_id, 'settings:ministry_categories:delete'
FROM public.church_role_permissions crp
WHERE crp.permission_key = 'settings:income_types:delete'
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ministry_category (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  church_id integer NOT NULL REFERENCES public.church (id) ON DELETE CASCADE,
  code text NOT NULL,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  sort_order integer NOT NULL DEFAULT 100,
  is_active boolean NOT NULL DEFAULT true,
  is_system boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ministry_category_church_code_unique UNIQUE (church_id, code),
  CONSTRAINT ministry_category_code_format CHECK (code ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT ministry_category_name_not_blank CHECK (length(trim(name)) > 0)
);

COMMENT ON TABLE public.ministry_category IS
  'Catálogo de categorías de ministerio por iglesia. Codes semánticos alimentan filtros y presets de asistencia.';

CREATE INDEX IF NOT EXISTS idx_ministry_category_church_active
  ON public.ministry_category (church_id, is_active, sort_order);

ALTER TABLE public.ministry_category ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ministry_category FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_ministry_category_select ON public.ministry_category;
DROP POLICY IF EXISTS tenant_ministry_category_insert ON public.ministry_category;
DROP POLICY IF EXISTS tenant_ministry_category_update ON public.ministry_category;
DROP POLICY IF EXISTS tenant_ministry_category_delete ON public.ministry_category;

CREATE POLICY tenant_ministry_category_select ON public.ministry_category
  FOR SELECT TO authenticated
  USING (church_id = public.fn_get_session_church_id());

CREATE POLICY tenant_ministry_category_insert ON public.ministry_category
  FOR INSERT TO authenticated
  WITH CHECK (church_id = public.fn_get_session_church_id());

CREATE POLICY tenant_ministry_category_update ON public.ministry_category
  FOR UPDATE TO authenticated
  USING (church_id = public.fn_get_session_church_id())
  WITH CHECK (church_id = public.fn_get_session_church_id());

CREATE POLICY tenant_ministry_category_delete ON public.ministry_category
  FOR DELETE TO authenticated
  USING (church_id = public.fn_get_session_church_id());

-- ---------------------------------------------------------------------------
-- Seed helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_seed_ministry_categories(p_church_id integer)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
BEGIN
  INSERT INTO public.ministry_category (
    church_id, code, name, description, sort_order, is_active, is_system
  )
  VALUES
    (p_church_id, 'discipleship', 'Discipulado',
     'Estudios bíblicos, escuela dominical y grupos de enseñanza.', 10, true, true),
    (p_church_id, 'house_group', 'Casas fuente',
     'Ministerios de casas / grupos en hogar.', 20, true, true),
    (p_church_id, 'cell_group', 'Célula',
     'Células o grupos pequeños de crecimiento.', 30, true, true),
    (p_church_id, 'children', 'Niños',
     'Ministerio infantil y escuela de niños.', 40, true, true),
    (p_church_id, 'worship', 'Adoración / culto',
     'Alabanza, culto y equipos de adoración.', 50, true, true),
    (p_church_id, 'other', 'Otro',
     'Categoría general u otros ministerios.', 90, true, true)
  ON CONFLICT (church_id, code) DO NOTHING;
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_fn_seed_ministry_categories()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
BEGIN
  PERFORM public.fn_seed_ministry_categories(NEW.id);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_church_seed_ministry_categories ON public.church;
CREATE TRIGGER trg_church_seed_ministry_categories
  AFTER INSERT ON public.church
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_fn_seed_ministry_categories();

-- Seed existing churches
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN SELECT id FROM public.church LOOP
    PERFORM public.fn_seed_ministry_categories(r.id);
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- Migrate church_ministries: drop CHECK → ensure codes → FK
-- ---------------------------------------------------------------------------

ALTER TABLE public.church_ministries
  DROP CONSTRAINT IF EXISTS church_ministries_ministry_category_check;

-- Ensure column exists (idempotent with 20260713240000)
ALTER TABLE public.church_ministries
  ADD COLUMN IF NOT EXISTS ministry_category text;

UPDATE public.church_ministries
SET ministry_category = 'other'
WHERE ministry_category IS NULL
   OR btrim(ministry_category) = ''
   OR ministry_category NOT IN (
     'discipleship', 'house_group', 'cell_group', 'children', 'worship', 'other'
   );

ALTER TABLE public.church_ministries
  ALTER COLUMN ministry_category SET DEFAULT 'other';

ALTER TABLE public.church_ministries
  ALTER COLUMN ministry_category SET NOT NULL;

-- Orphan custom codes that somehow exist: map to other before FK
UPDATE public.church_ministries cm
SET ministry_category = 'other'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.ministry_category mc
  WHERE mc.church_id = cm.church_id
    AND mc.code = cm.ministry_category
);

ALTER TABLE public.church_ministries
  DROP CONSTRAINT IF EXISTS church_ministries_ministry_category_fk;

ALTER TABLE public.church_ministries
  ADD CONSTRAINT church_ministries_ministry_category_fk
  FOREIGN KEY (church_id, ministry_category)
  REFERENCES public.ministry_category (church_id, code)
  ON UPDATE CASCADE
  ON DELETE RESTRICT;

COMMENT ON COLUMN public.church_ministries.ministry_category IS
  'Code de ministry_category (FK church_id+code). Seeds: discipleship|house_group|cell_group|children|worship|other + custom.';

CREATE INDEX IF NOT EXISTS idx_church_ministries_church_category
  ON public.church_ministries (church_id, ministry_category);
